# Generated by Django 2.0.3 on 2020-06-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200616_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
