# Generated by Django 2.0.3 on 2020-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200618_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
