# Generated by Django 2.0.3 on 2020-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200618_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('large', 'Large'), ('large', 'Small')], max_length=5, null=True),
        ),
    ]
