# Generated by Django 2.0.3 on 2020-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200618_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('T', 'Topping'), ('Sub', 'Sub'), ('Pasta', 'Pasta'), ('Dinner Platter', 'Dinner Platter'), ('Salad', 'Salad')], max_length=2),
        ),
    ]
