# Generated by Django 2.0.3 on 2020-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200618_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('RP', 'Regular Pizza'), ('SP', 'Sicilian Pizza'), ('T', 'Topping'), ('S', 'Sub'), ('P', 'Pasta'), ('D', 'Dinner Platter'), ('Sa', 'Salad')], max_length=2),
        ),
    ]
