# Generated by Django 2.0.3 on 2020-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200618_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug_small',
            field=models.SlugField(default='-small'),
            preserve_default=False,
        ),
    ]
