# Generated by Django 2.0.3 on 2020-06-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_item_slug_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug_small',
        ),
    ]
