# Generated by Django 2.0.3 on 2020-06-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_item_slug_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('Large', 'Large'), ('Small', 'Small')], max_length=5, null=True),
        ),
    ]
