# Generated by Django 2.0.3 on 2020-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='item',
        ),
        migrations.AddField(
            model_name='topping',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Item'),
        ),
    ]
