# Generated by Django 3.0.7 on 2020-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20200619_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='toppings',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='Item', to='orders.Topping'),
        ),
    ]
