# Generated by Django 3.0.7 on 2020-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200619_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='OrderItem', to='orders.Topping'),
        ),
    ]
