# Generated by Django 3.0.7 on 2020-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200619_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='topping',
            name='orderitems',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.OrderItem'),
        ),
    ]
