# Generated by Django 2.0.3 on 2020-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200619_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='topping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
