# Generated by Django 2.0.3 on 2020-06-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_remove_item_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Topping', 'Topping'), ('Sub', 'Sub'), ('Pasta', 'Pasta'), ('Dinner Platter', 'Dinner Platter'), ('Salad', 'Salad')], max_length=2),
        ),
    ]
