# Generated by Django 2.0.3 on 2020-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20200621_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug_small',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
